### ISSUE TITLE
Add support for .NET 8

### ISSUE THREAD

**Issue by aevitas** [aevitas/flakeid#10]
.NET 8 has been released a few months ago, and especially because this is an LTS release, FlakeId should support it.

Currently the library targets:
```
<TargetFrameworks>net7.0;net6.0;net5.0;netstandard2.1</TargetFrameworks>
```

This should be updated to also include the `net8.0` moniker. Additionally the CI build and tests should also run on .NET 8.0.

**Comment by romadanskiy** [comment]
Hello! I think I can help you with this. 😄  
I'll try to open PR soon.
